config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about", to: "pages#about"
  get "testimonies", to: "pages#testimonies"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home about testimonies]

  def home
    @bom = book_of_mormon
  end

  def about
    @bom = book_of_mormon
  end

  def testimonies
    @bom = book_of_mormon
    @bom_data = word_counter(@bom['testimonies'][0]['text'])
    @bom_data2 = word_counter(@bom['testimonies'][1]['text'])
  end

  private

  def book_of_mormon
    require 'open-uri'
    json = File.join(__dir__, "../../book_of_mormon.json")
    JSON.parse(File.read(json))
  end

  def word_counter(text)
    stop_words = %w[the and of to in a that it is was i for he you as his with be not are this but they on have at by she or an we do from which one would all will there say who make when can more if unto our also us]

    text.tr('.,;:?!', '').split.map(&:downcase).reject { |w| stop_words.include? w }.tally.sort_by { |_, v| -v }.to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bom2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @bom['title'] %></h1>
<h2><%= @bom['title_page']['subtitle'] %></h2>
<% @bom['title_page']['text'].each do |paragraph| %>
  <h4><%= paragraph %></h4>
  <br>
<% end %>
<br>
<h2><%= @bom['title_page']['translated_by'] %></h2>

app/views/pages/home.html.erb
<h1><%= @bom["title"] %></h1>

<h2><%= @bom['subtitle'] %></h2>

app/views/pages/testimonies.html.erb
<h1><%= @bom_data %></h1>
<h1><%= @bom_data2 %></h1>

<h1><%= @bom['testimonies'].first['title'] %></h1>
<h2><%= @bom['testimonies'].first['text'] %></h2>
<ul class="list-unstyled">
  <% @bom['testimonies'][0]['witnesses'].each do |witness| %>
    <h3><%= witness %></h3>
  <% end %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn6.aptoide.com/imgs/7/4/3/7434e10c32b84557da1d2ccc37ab64d7_icon.png", style: 'width: 80px;' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Testimonies', testimonies_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>